### ISSUE TITLE
java cli default argument -Xss8G causes a crash

### ISSUE THREAD

**Issue by iharsuvorau** [AdaptiveBProcess/Simod#13]
@Mcamargo85 

On macOS 11.4 with java:

```
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

running `python simod_console.py` fails with:

```
 -- Mining Process Structure --
Invalid thread stack size: -Xss8G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[Errno 2] No such file or directory: 'outputs/20210701_8512596F_0181_4932_89A5_87F7430B474D/PurchasingExample.bpmn'
```

Java tool failed because of `-Xss8G`. Changing it to a smaller number `-Xms1024M` works okay.

**Comment by Mcamargo85** [comment]
Issue solved with the java parameters update

**Comment by iharsuvorau** [comment]
@Mcamargo85 

Yes, issue is solved when you manually change java parameters in code, but should we expect every user to do so before the run? Should we mention it in the documentation? Is it possible to recognize this parameter depending on the environment?

**Comment by Mcamargo85** [comment]
I think that for the moment, you can leave default parameters depending on the environment. However, this should not be a problem in the future because it is related to the java virtual machine, and precisely the idea is to remove the dependency with java.

**Comment by iharsuvorau** [comment]
@Mcamargo85 Great, thanks. Now it's clear.
