### ISSUE TITLE
Self-assignment in extraction/log_replayer.py

### ISSUE THREAD

**Issue by iharsuvorau** [AdaptiveBProcess/Simod#16]
Hi, @Mcamargo85

Going through the code with Sonarqube code analysis tool, it complains at this line marking it as a bug:

https://github.com/AdaptiveBProcess/Simod/blob/31acdb14223297fc798b1d4903e0960250141e0a/extraction/log_replayer.py#L129

Do you agree that this line is redundant?

**Comment by Mcamargo85** [comment]
Hi Ihar,

I think it is probably an error in the variable's names. I guess that the pnode element in the for needs a different name. For sure, the whole structure needs a better syntaxis using with or something like that, but just the renaming should be enough by the moment. In any case, I think the whole module will be discarded.

Regards,
Manuel


From: Ihar Suvorau ***@***.***>
Sent: Tuesday, July 27, 2021 12:32 PM
To: AdaptiveBProcess/Simod ***@***.***>
Cc: Manuel Alejandro Camargo Chavez ***@***.***>; Mention ***@***.***>
Subject: [AdaptiveBProcess/Simod] Self-asignment in extraction/log_replayer.py (#16)


Hi, @Mcamargo85<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMcamargo85&data=04%7C01%7Cma.camargo11%40uniandes.edu.co%7C4e9dd731bdff46db9ee208d950e15395%7Cfabd047cff48492a8bbb8f98b9fb9cca%7C0%7C0%7C637629750983905839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IfBKIQ2M%2FvgOzrfXJzEOinz3zhfjPEhRNxeOxFj%2B6as%3D&reserved=0>

Going through the code with Sonarqube code analysis tool, it complains at this line marking it as a bug:

https://github.com/AdaptiveBProcess/Simod/blob/31acdb14223297fc798b1d4903e0960250141e0a/extraction/log_replayer.py#L129<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdaptiveBProcess%2FSimod%2Fblob%2F31acdb14223297fc798b1d4903e0960250141e0a%2Fextraction%2Flog_replayer.py%23L129&data=04%7C01%7Cma.camargo11%40uniandes.edu.co%7C4e9dd731bdff46db9ee208d950e15395%7Cfabd047cff48492a8bbb8f98b9fb9cca%7C0%7C0%7C637629750983915793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7nLdtPi2f9RnmWp%2FaRvvVyxaKMugKa5Sswlbt9EBYgw%3D&reserved=0>

Do you agree that this line is redundant?

-

**Comment by iharsuvorau** [comment]
Thanks, I'll fix this in my branch.
