### ISSUE TITLE
Statement seems to have no effect

### ISSUE THREAD

**Issue by iharsuvorau** [AdaptiveBProcess/Simod#17]
Hey, @Mcamargo85,

Does `next` mean `continue` in this for-loop?

https://github.com/AdaptiveBProcess/Simod/blob/31acdb14223297fc798b1d4903e0960250141e0a/support_modules/writers/xes_writer.py#L101

**Comment by Mcamargo85** [comment]
Hi!

Yeah, it means continue Jaja, but it seems like it was an uncommented line about a possible transition that I didn't solve. In any case, is continue.

Regards,
Manuel

From: Ihar Suvorau ***@***.***>
Sent: Tuesday, July 27, 2021 2:15 PM
To: AdaptiveBProcess/Simod ***@***.***>
Cc: Manuel Alejandro Camargo Chavez ***@***.***>; Mention ***@***.***>
Subject: [AdaptiveBProcess/Simod] Statement seems to have no effect (#17)


Hey, @Mcamargo85<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMcamargo85&data=04%7C01%7Cma.camargo11%40uniandes.edu.co%7Cdc92736202824d66c54308d950efba04%7Cfabd047cff48492a8bbb8f98b9fb9cca%7C0%7C0%7C637629812809886686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2glYQQBvdlEeVqztFe%2B%2BWSIxjrQoe%2BCeFmaRetXMGuY%3D&reserved=0>,

Does next mean continue in this for-loop?

https://github.com/AdaptiveBProcess/Simod/blob/31acdb14223297fc798b1d4903e0960250141e0a/support_modules/writers/xes_writer.py#L101<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdaptiveBProcess%2FSimod%2Fblob%2F31acdb14223297fc798b1d4903e0960250141e0a%2Fsupport_modules%2Fwriters%2Fxes_writer.py%23L101&data=04%7C01%7Cma.camargo11%40uniandes.edu.co%7Cdc92736202824d66c54308d950efba04%7Cfabd047cff48492a8bbb8f98b9fb9cca%7C0%7C0%7C637629812809886686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cMLXbT9YAx9ntYvLzS0cGnisgJlPyJwUv6YRGxxzzN8%3D&reserved=0>

-
